CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    senha_hash TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.pagamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES public.usuarios(id),
    nome TEXT NOT NULL,
    data_pagamento DATE NOT NULL,
    data_vencimento DATE,
    valor NUMERIC(12,2) NOT NULL DEFAULT 0,
    juros NUMERIC(12,2) NOT NULL DEFAULT 0,
    observacao TEXT,
    data_pago DATE,
    cancelado_em TIMESTAMPTZ,
    atualizado_em TIMESTAMPTZ DEFAULT NOW(),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Colunas adicionadas em versões anteriores (seguro rodar mesmo se já existirem)
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS usuario_id BIGINT REFERENCES public.usuarios(id);
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS data_vencimento DATE;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS observacao TEXT;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS data_pago DATE;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS cancelado_em TIMESTAMPTZ;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMPTZ DEFAULT NOW();

-- Colunas de controle de e-mail
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS email_vencimento_enviado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS email_proximo_enviado BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE public.pagamentos
SET data_vencimento = (data_pagamento + INTERVAL '1 month')::date
WHERE data_vencimento IS NULL;

CREATE INDEX IF NOT EXISTS idx_pagamentos_usuario ON public.pagamentos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_vencimento ON public.pagamentos(data_vencimento);
CREATE INDEX IF NOT EXISTS idx_pagamentos_data_pago ON public.pagamentos(data_pago);
