CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    senha_hash TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.pagamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES public.usuarios(id),
    nome TEXT NOT NULL,
    data_pagamento DATE NOT NULL,
    data_vencimento DATE,
    valor NUMERIC(12,2) NOT NULL DEFAULT 0,
    juros NUMERIC(12,2) NOT NULL DEFAULT 0,
    observacao TEXT,
    data_pago DATE,
    cancelado_em TIMESTAMPTZ,
    atualizado_em TIMESTAMPTZ DEFAULT NOW(),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    comprovante_nome TEXT,
    comprovante_tipo TEXT,
    comprovante_dados BYTEA
);

-- Colunas adicionadas em versões anteriores (seguro rodar mesmo se já existirem)
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS usuario_id BIGINT REFERENCES public.usuarios(id);
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS data_vencimento DATE;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS observacao TEXT;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS data_pago DATE;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS cancelado_em TIMESTAMPTZ;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMPTZ DEFAULT NOW();

-- Colunas de controle de e-mail
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS email_vencimento_enviado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS email_proximo_enviado BOOLEAN NOT NULL DEFAULT FALSE;

-- Comprovante de pagamento (foto ou PDF), guardado direto no banco
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS comprovante_nome TEXT;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS comprovante_tipo TEXT;
ALTER TABLE public.pagamentos ADD COLUMN IF NOT EXISTS comprovante_dados BYTEA;

UPDATE public.pagamentos
SET data_vencimento = (data_pagamento + INTERVAL '1 month')::date
WHERE data_vencimento IS NULL;

CREATE INDEX IF NOT EXISTS idx_pagamentos_usuario ON public.pagamentos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_vencimento ON public.pagamentos(data_vencimento);
CREATE INDEX IF NOT EXISTS idx_pagamentos_data_pago ON public.pagamentos(data_pago);

-- ── Clientes ────────────────────────────────────────────────────────────────
-- Cadastro de clientes (foto + limite de credito), vinculado ao historico de
-- emprestimos em public.pagamentos pelo nome (mesma normalizacao: trim+upper).

CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    nome TEXT NOT NULL,
    limite_credito NUMERIC(12,2),
    observacao TEXT,
    foto_nome TEXT,
    foto_tipo TEXT,
    foto_dados BYTEA,
    cancelado_em TIMESTAMPTZ,
    atualizado_em TIMESTAMPTZ DEFAULT NOW(),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (usuario_id, nome)
);

CREATE INDEX IF NOT EXISTS idx_clientes_usuario ON public.clientes(usuario_id);

-- ── Gastos pessoais (regra 50/30/20) ─────────────────────────────────────────
-- Aba separada do controle de emprestimos: orcamento definido pelo que entra
-- no mes (renda_mensal), nao pelo saldo disponivel.

CREATE TABLE IF NOT EXISTS public.renda_mensal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    mes DATE NOT NULL,
    valor NUMERIC(12,2) NOT NULL DEFAULT 0,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (usuario_id, mes)
);

CREATE TABLE IF NOT EXISTS public.gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    descricao TEXT NOT NULL,
    categoria TEXT NOT NULL CHECK (categoria IN ('NECESSIDADE','LAZER','RESERVA')),
    valor NUMERIC(12,2) NOT NULL DEFAULT 0,
    data DATE NOT NULL,
    observacao TEXT,
    cancelado_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_renda_usuario ON public.renda_mensal(usuario_id);
CREATE INDEX IF NOT EXISTS idx_gastos_usuario ON public.gastos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_gastos_data ON public.gastos(data);
